language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t spra100/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true spra100/docker-react npm run test
